# Generated by Django 2.2.3 on 2019-07-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_post_client_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
