# Generated by Django 2.2.3 on 2019-07-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_post_client_linkedinurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='client_linkedinurl',
            field=models.CharField(default='www.', max_length=150),
        ),
    ]
