# Generated by Django 2.2.3 on 2019-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20190723_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client_notes',
            field=models.TextField(default='Notes Here...'),
        ),
        migrations.AlterField(
            model_name='post',
            name='client_linkedinurl',
            field=models.CharField(default='Linkedin Profile...', max_length=150),
        ),
    ]
