# Generated by Django 2.2.3 on 2019-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20190731_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='client_products',
            field=models.CharField(choices=[('Analytics', 'Analytics Only'), ('Datafeeds', 'Datafeeds Only'), ('Analytics, Datafeeds', 'Analytics & Datafeeds'), ('MRT', 'Media Ratings Tool')], max_length=100),
        ),
    ]
