# Generated by Django 2.2.3 on 2019-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20190731_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client_qaresults',
            field=models.CharField(default='', max_length=100),
        ),
    ]
